# Generated by Django 5.2.1 on 2025-06-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct')], help_text='Select the conservation status of the species.', max_length=2)),
                ('description', models.TextField(help_text='Provide a description explaining the selected conservation status.')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=100)),
                ('soil_pH', models.FloatField()),
                ('fertility_level', models.CharField(max_length=100)),
                ('rainfall_mm', models.FloatField()),
                ('temperature_c', models.FloatField()),
                ('water_source_proximity', models.CharField(max_length=100)),
                ('biodiversity_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(blank=True, help_text='A featured image for the heritage site.', upload_to='heri_imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255, unique=True)),
                ('common_name', models.CharField(max_length=255)),
                ('family', models.CharField(blank=True, max_length=255, null=True)),
                ('iucn_status', models.CharField(blank=True, choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct')], max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('ranger', 'Ranger'), ('researcher', 'Researcher'), ('public', 'Public')], max_length=50)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeritageSiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='heri_imgs/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('heritage_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heritage_site_images', to='ind_trees.heritagesite')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_hectares', models.FloatField(blank=True)),
                ('land_ownership', models.CharField(choices=[('protected', 'Protected Area'), ('private', 'Private Land'), ('communal', 'Communal Land')], max_length=50)),
                ('protection_status', models.CharField(choices=[('protected', 'Protected'), ('vulnerable', 'Vulnerable'), ('remediation', 'Remediation Zone')], max_length=50)),
                ('zone_type', models.CharField(choices=[('conservation', 'Conservation Forest'), ('communal', 'Communal Land'), ('municipal', 'Municipal Area')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('boundary_coordinates', models.JSONField(blank=True, null=True)),
                ('land_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_data', to='ind_trees.environmentaldata')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_days', models.PositiveIntegerField(help_text='Days between monitoring')),
                ('next_due', models.DateField()),
                ('assigned_to', models.CharField(max_length=255)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ind_trees.plot')),
            ],
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='ind_trees.plot'),
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=255)),
                ('legal_status', models.CharField(max_length=255)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ind_trees.plot')),
            ],
        ),
        migrations.CreateModel(
            name='PlotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plot_imgs/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ind_trees.plot')),
            ],
        ),
        migrations.CreateModel(
            name='PlotMonitoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitored_at', models.DateTimeField(auto_now_add=True)),
                ('monitored_by', models.CharField(help_text='Name of the ranger, researcher, or organization.', max_length=255)),
                ('vegetation_cover', models.TextField(blank=True, help_text='General observation on vegetation cover, changes, or degradation.')),
                ('invasive_species_present', models.BooleanField(default=False)),
                ('invasive_species_details', models.TextField(blank=True, help_text='Details of observed invasive species, if any.')),
                ('signs_of_deforestation', models.BooleanField(default=False)),
                ('signs_of_fire', models.BooleanField(default=False)),
                ('illegal_activities_observed', models.TextField(blank=True, help_text='E.g., poaching, illegal logging, charcoal burning')),
                ('wildlife_presence', models.TextField(blank=True, help_text='Observed wildlife species or evidence of wildlife')),
                ('soil_erosion_signs', models.BooleanField(default=False)),
                ('erosion_notes', models.TextField(blank=True)),
                ('water_conditions', models.TextField(blank=True, help_text='Condition of nearby water sources, wetness, pollution signs, etc.')),
                ('human_activity_notes', models.TextField(blank=True, help_text='Encroachment, grazing, settlements, road construction, etc.')),
                ('threats_identified', models.TextField(blank=True)),
                ('recommended_actions', models.TextField(blank=True)),
                ('weather_conditions', models.CharField(blank=True, help_text='Weather during monitoring (e.g., sunny, rainy)', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('monitoring_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ind_trees.monitoringschedule')),
                ('plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='ind_trees.plot')),
            ],
            options={
                'ordering': ['-monitored_at'],
            },
        ),
        migrations.CreateModel(
            name='PlotMonitoringPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plot_monitoring_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('monitoring_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ind_trees.plotmonitoringrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('last_monitored', models.DateField(blank=True, null=True)),
                ('tree_description', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('pros', models.TextField(blank=True, help_text='Benefits of the tree.')),
                ('cons', models.TextField(blank=True, help_text='Challenges associated with the tree.')),
                ('medical_benefits', models.TextField(blank=True, help_text='Traditional medicinal uses.')),
                ('general_use', models.TextField(blank=True, help_text='Applications such as timber, crafting, etc.')),
                ('cultural_significance', models.TextField(blank=True, help_text='Symbolic or spiritual importance.')),
                ('location', models.CharField(help_text='Geographical areas where found.', max_length=200)),
                ('ecological_role', models.TextField(blank=True, help_text="Tree's role in biodiversity, soil health, ecosystem stability.")),
                ('threats_and_conservation_efforts', models.TextField(blank=True, help_text='Threats and ongoing conservation efforts.')),
                ('myths', models.TextField(blank=True, help_text='Traditional stories and folklore.')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('categories', models.ManyToManyField(help_text='Categories this tree belongs to.', to='ind_trees.category')),
                ('conservation_status', models.ForeignKey(help_text='Conservation status of the tree.', on_delete=django.db.models.deletion.CASCADE, to='ind_trees.conservationstatus')),
                ('heritage_sites', models.ManyToManyField(blank=True, help_text='Heritage sites associated with this tree.', to='ind_trees.heritagesite')),
                ('plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ind_trees.plot')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ind_trees.species')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatsConservationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='threats_conservation_imgs/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats_conservation_images', to='ind_trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalBenefitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medical_benefit_imgs/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_benefit_images', to='ind_trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalSignificanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cultural_significance_imgs/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_significance_images', to='ind_trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tree_imgs/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ind_trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('planting', 'Planting'), ('pruning', 'Pruning'), ('disease_control', 'Disease Control'), ('fencing', 'Fencing'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('observer', models.CharField(max_length=255)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='ind_trees.tree')),
            ],
        ),
        migrations.AddField(
            model_name='plotmonitoringrecord',
            name='intervention',
            field=models.ForeignKey(blank=True, help_text='Intervention action taken on the plot level.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ind_trees.treeintervention'),
        ),
        migrations.CreateModel(
            name='TreeMonitoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitored_at', models.DateTimeField(auto_now_add=True)),
                ('monitored_by', models.CharField(help_text='Name of the person or organization.', max_length=100)),
                ('alive_count', models.PositiveIntegerField(default=0, help_text='Number of surviving trees (if group).')),
                ('dead_count', models.PositiveIntegerField(default=0, help_text='How many trees have died (if any).')),
                ('health_status', models.CharField(help_text='E.g., Healthy, Diseased, Pest-infested, Drying', max_length=100)),
                ('threats_observed', models.TextField(blank=True)),
                ('conservation_actions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('intervention', models.ForeignKey(blank=True, help_text='interventions done on trees', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ind_trees.treeintervention')),
                ('monitoring_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ind_trees.monitoringschedule')),
                ('plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ind_trees.plot')),
                ('trees', models.ManyToManyField(related_name='monitoring_records', to='ind_trees.tree')),
            ],
            options={
                'ordering': ['-monitored_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeMonitoringPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='monitoring_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('monitoring_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ind_trees.treemonitoringrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TreePlantingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planted', models.PositiveIntegerField(default=1, help_text='Number of this tree species planted in the event')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ind_trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreePlantingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the planting event or project.', max_length=255)),
                ('organizer', models.CharField(help_text='Organization or individual who organized the planting.', max_length=255)),
                ('location', models.CharField(help_text='Where the event took place.', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_planted', models.DateField()),
                ('number_of_trees_planted', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_data', to='ind_trees.plot')),
                ('trees', models.ManyToManyField(blank=True, related_name='planting_events', through='ind_trees.TreePlantingDetail', to='ind_trees.tree')),
            ],
        ),
        migrations.AddField(
            model_name='treeplantingdetail',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ind_trees.treeplantingevent'),
        ),
        migrations.AddField(
            model_name='treemonitoringrecord',
            name='planting_event',
            field=models.ForeignKey(blank=True, help_text='Optional link to the planting event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ind_trees.treeplantingevent'),
        ),
        migrations.CreateModel(
            name='TreePlantingEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='planting_event_imgs/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ind_trees.treeplantingevent')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredTreeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive_count', models.PositiveIntegerField(default=0)),
                ('dead_count', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, help_text='Optional notes about this tree species', max_length=255)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ind_trees.tree')),
                ('monitoring_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_trees', to='ind_trees.treemonitoringrecord')),
            ],
            options={
                'unique_together': {('monitoring_record', 'tree')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='treeplantingdetail',
            unique_together={('tree', 'event')},
        ),
    ]
