# Generated by Django 5.2.1 on 2025-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeplantingdetail',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='treeplantingdetail',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
