# Generated by Django 5.2.1 on 2025-11-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_trees', '0002_treeplantingdetail_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotmonitoringrecord',
            name='air_quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotmonitoringrecord',
            name='next_monitoring_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plotmonitoringrecord',
            name='water_quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
