# Generated by Django 5.2.1 on 2025-07-16 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_trees', '0001_initial'),
        ('stakeholder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeReportCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_report', models.TextField()),
                ('ai_summary', models.TextField()),
                ('last_generated', models.DateTimeField(auto_now=True)),
                ('last_monitoring_at', models.DateTimeField(blank=True, null=True)),
                ('tree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_report', to='ind_trees.tree')),
            ],
        ),
    ]
