# Generated by Django 5.2.1 on 2025-11-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0002_treereportcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='treereportcache',
            name='map_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treereportcache',
            name='map_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treereportcache',
            name='survival_trend_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
