# Generated by Django 5.2.1 on 2025-11-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0003_treereportcache_map_lat_treereportcache_map_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treereportcache',
            name='survival_trend_alive',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='treereportcache',
            name='survival_trend_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='treereportcache',
            name='survival_trend_dead',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
