# Generated by Django 5.2.1 on 2025-11-20 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_trees', '0003_plotmonitoringrecord_air_quality_and_more'),
        ('stakeholder', '0004_treereportcache_survival_trend_alive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEEPlotAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GEEAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ndvi_mean', models.FloatField(blank=True, null=True)),
                ('ndvi_min', models.FloatField(blank=True, null=True)),
                ('ndvi_max', models.FloatField(blank=True, null=True)),
                ('evi_mean', models.FloatField(blank=True, null=True)),
                ('tree_cover_percent', models.FloatField(blank=True, null=True)),
                ('canopy_density', models.FloatField(blank=True, null=True)),
                ('forest_loss_hectares', models.FloatField(blank=True, null=True)),
                ('forest_gain_hectares', models.FloatField(blank=True, null=True)),
                ('biomass_estimate', models.FloatField(blank=True, null=True)),
                ('carbon_stock_estimate', models.FloatField(blank=True, null=True)),
                ('fire_hotspots', models.IntegerField(blank=True, null=True)),
                ('burned_area_hectares', models.FloatField(blank=True, null=True)),
                ('fire_severity_index', models.FloatField(blank=True, null=True)),
                ('ndwi_mean', models.FloatField(blank=True, null=True)),
                ('water_presence_percent', models.FloatField(blank=True, null=True)),
                ('flood_extent_hectares', models.FloatField(blank=True, null=True)),
                ('soil_moisture_index', models.FloatField(blank=True, null=True)),
                ('bare_soil_index', models.FloatField(blank=True, null=True)),
                ('erosion_risk', models.CharField(blank=True, max_length=50, null=True)),
                ('elevation_mean', models.FloatField(blank=True, null=True)),
                ('slope_mean', models.FloatField(blank=True, null=True)),
                ('rainfall_mm_recent', models.FloatField(blank=True, null=True)),
                ('temperature_c_recent', models.FloatField(blank=True, null=True)),
                ('drought_index', models.FloatField(blank=True, null=True)),
                ('landcover_summary', models.JSONField(blank=True, null=True)),
                ('encroachment_detected', models.BooleanField(default=False)),
                ('encroachment_details', models.TextField(blank=True, null=True)),
                ('habitat_fragmentation_score', models.FloatField(blank=True, null=True)),
                ('vegetation_diversity_index', models.FloatField(blank=True, null=True)),
                ('aerosol_optical_depth', models.FloatField(blank=True, null=True)),
                ('smoke_presence_probability', models.FloatField(blank=True, null=True)),
                ('raw_gee_data', models.JSONField(blank=True, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gee_analysis', to='ind_trees.plot')),
            ],
        ),
        migrations.CreateModel(
            name='GEEAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gee_history', to='ind_trees.plot')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholder.geeplotanalysis')),
            ],
        ),
    ]
