# Generated by Django 5.2.1 on 2025-11-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0005_geeplotanalysis_geeanalysis_geeanalysishistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeplotanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='geeplotanalysis',
            name='raw_gee_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
