# Generated by Django 5.2.1 on 2025-11-20 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_trees', '0003_plotmonitoringrecord_air_quality_and_more'),
        ('stakeholder', '0006_geeplotanalysis_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeplotanalysis',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gee_snapshots', to='ind_trees.plot'),
        ),
        migrations.AlterField(
            model_name='geeanalysishistory',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='stakeholder.geeplotanalysis'),
        ),
    ]
