# Generated by Django 5.2.1 on 2025-11-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0007_geeplotanalysis_plot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geeanalysis',
            options={'ordering': ['-analyzed_at']},
        ),
        migrations.AlterModelOptions(
            name='geeanalysishistory',
            options={'ordering': ['-archived_at']},
        ),
        migrations.AlterModelOptions(
            name='geeplotanalysis',
            options={'ordering': ['-created_at']},
        ),
    ]
