# Generated by Django 5.2.1 on 2025-11-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0008_alter_geeanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeanalysis',
            name='alerts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geeanalysis',
            name='evapotranspiration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geeanalysis',
            name='post_fire_recovery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geeanalysis',
            name='shannon_diversity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geeanalysis',
            name='simpson_diversity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
