# Generated by Django 5.2.1 on 2026-05-22 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_trees', '0003_plotmonitoringrecord_air_quality_and_more'),
        ('stakeholder', '0009_geeanalysis_alerts_geeanalysis_evapotranspiration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_report', models.TextField()),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_monitoring_at', models.DateTimeField(blank=True, null=True)),
                ('survival_trend_dates', models.JSONField(blank=True, default=list)),
                ('survival_trend_alive', models.JSONField(blank=True, default=list)),
                ('survival_trend_dead', models.JSONField(blank=True, default=list)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_history', to='ind_trees.tree')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
