# Generated by Django 5.2.1 on 2026-05-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0010_treereporthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='treereportcache',
            name='monitoring_points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treereporthistory',
            name='last_generated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='treereporthistory',
            name='map_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treereporthistory',
            name='map_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treereporthistory',
            name='monitoring_points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
