# Generated by Django 5.2.1 on 2026-05-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_trees', '0003_plotmonitoringrecord_air_quality_and_more'),
        ('stakeholder', '0011_treereportcache_monitoring_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReportCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_report', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('last_generated', models.DateTimeField(auto_now=True)),
                ('last_monitoring_at', models.DateTimeField(blank=True, null=True)),
                ('total_trees_planted', models.IntegerField(default=0)),
                ('survival_rate', models.FloatField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_report', to='ind_trees.treeplantingevent')),
            ],
        ),
        migrations.CreateModel(
            name='EventReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_report', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_monitoring_at', models.DateTimeField(blank=True, null=True)),
                ('total_trees_planted', models.IntegerField(default=0)),
                ('survival_rate', models.FloatField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_history', to='ind_trees.treeplantingevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
